name: React Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: building
        run: npm run dev
      - name: test passes
        run: echo "working all test passes"